#!/usr/bin/env node
// End-to-end: a written report is relayed like a person would say it
// (SPEC §8.1 "How you talk", §6.10), against the REAL gpt-live-1.
//
// Live on 2026-09-24 the voice read Claude's markdown reports nearly verbatim
// ("Claude Code's answer: …", labels, lists) and closed with stock lines ("No
// input needed from you."). This asks a question through the fake mic, lets
// the model delegate it, then answers with a markdown-heavy Stop (bold labels,
// bullets, file paths, a stock tag line) through the real hook.sh, and checks
// what the voice said about it: no "Claude Code's answer", no "bullet" or
// "asterisk", no file path, no tag line, no banned opener, under ~45 words,
// and still the key fact (the fixture is called banana split).
//
// Needs: OPENAI_API_KEY (env or <repo>/.env), Google Chrome, ffmpeg.
// Cost: one Live session, about 25-35 billed seconds (~$0.03).
//
//   npm run e2e:relay
//   SOTTO_E2E_RELAY_PORT=47893   daemon port
//   SOTTO_E2E_KEEP=1             keep the temp dir (logs)
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { startFakeInbox } from "../helpers/fake-inbox.js";
import { CHROME, spawnSilentChrome } from "../helpers/silent-chrome.js";
import { resolveApiKey } from "../../daemon/config.js";
import { isBannedOpener } from "../../daemon/stylewatch.js";
import { isTagline } from "../../daemon/phrasing.js";

const REPO = fileURLToPath(new URL("../..", import.meta.url)).replace(/\/$/, "");
const PORT = Number(process.env.SOTTO_E2E_RELAY_PORT || 47893);
const BASE = `http://127.0.0.1:${PORT}`;
const FIXTURE = path.join(REPO, "test", "fixtures", "ask-files.wav"); // "What files are in this project?"
const SOCK = `/tmp/clv-e2e-relay-${process.pid}.sock`;
const INBOX_TOKEN = `e2e-relay-token-${process.pid}`;
const TMP = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "clv-e2e-relay-")));
const D = path.join(TMP, "data");
const LIVE_BUDGET_MS = 75_000;
const LEAD_MS = 8000;
const MAX_WORDS = 45;

// The shape of report that sounded robotic read aloud.
const REPORT = [
  "**Found it.** The test fixture is called **banana split**.",
  "",
  "**Details:**",
  "- **Fixture:** `/Users/me/dev/sotto/test/fixtures/banana-split.wav` (48 kHz, mono)",
  "- **Used by:** `test/e2e/smoke.mjs` and `test/e2e/relay.mjs`",
  "- **Generated by:** `test/e2e/make-fixture.mjs`",
  "",
  "No input needed from you.",
].join("\n");

const results = [];
const timings = {};
let inbox;
let chrome;
let liveId = null;
let billed = null;
let liveSince = 0;

const log = (...a) => console.log("[e2e-relay]", ...a);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
function check(name, ok, detail = "") {
  results.push({ name, ok: !!ok, detail });
  log(`${ok ? "PASS" : "FAIL"} ${name}${detail ? " - " + detail : ""}`);
  return !!ok;
}
async function until(fn, ms, every = 200) {
  const end = Date.now() + ms;
  for (;;) {
    try { const v = await fn(); if (v) return v; } catch { /* retry */ }
    if (Date.now() > end) return null;
    await sleep(every);
  }
}
const readLog = () => {
  try {
    return fs.readFileSync(path.join(D, "logs", "daemon.log"), "utf8").split("\n").filter(Boolean)
      .map((l) => { try { return JSON.parse(l); } catch { return null; } }).filter(Boolean);
  } catch { return []; }
};
const ts = (e) => Date.parse(e.ts);
const secs = (ms) => (ms / 1000).toFixed(2) + " s";
let KEY = "";
const hdr = () => ({ "Content-Type": "application/json", "X-Sotto-Key": KEY });
const status = async () => (await fetch(`${BASE}/status`, { headers: hdr() })).json();

function hookEnv() {
  const env = {};
  for (const [k, v] of Object.entries(process.env)) if (!/^CLAUDE_/.test(k)) env[k] = v;
  return Object.assign(env, {
    CLAUDE_PLUGIN_ROOT: REPO, CLAUDE_PLUGIN_DATA: D, CLAUDE_PLUGIN_OPTION_PORT: String(PORT),
    CLAUDE_PLUGIN_OPTION_DAILY_CAP_MINUTES: "10", CLAUDE_PLUGIN_OPTION_IDLE_SECONDS: "0",
    CLAUDE_CODE_MESSAGING_SOCKET: SOCK, CLAUDE_CODE_MESSAGING_TOKEN: INBOX_TOKEN, CLAUDE_PROJECT_DIR: REPO,
    SOTTO_NO_BROWSER: "1",
    SOTTO_UPDATE: "0", // an edit to this checkout mid-run must not restart the test daemon
    SOTTO_KEYCHAIN_SERVICE: `sotto-e2e-relay-${process.pid}`, // never the user's real Keychain item
  });
}
function toggle(arg) {
  const input = JSON.stringify({
    session_id: "e2e-relay", transcript_path: "", cwd: REPO, prompt_id: "p", permission_mode: "default",
    hook_event_name: "UserPromptExpansion", expansion_type: "slash_command", command_name: "sotto:talk",
    command_args: arg, command_source: "plugin", prompt: `/sotto:talk ${arg}`.trim(),
  });
  const r = spawnSync(path.join(REPO, "scripts", "toggle.sh"), [], { input, encoding: "utf8", env: hookEnv(), timeout: 15000 });
  let out = null;
  try { out = JSON.parse(r.stdout); } catch { /* checked by caller */ }
  return { status: r.status, out };
}
const hook = (event, body) => spawnSync(path.join(REPO, "scripts", "hook.sh"), [event], { input: JSON.stringify(body), encoding: "utf8", env: hookEnv() });
function daemonPid() { try { return Number(fs.readFileSync(path.join(D, "daemon.pid"), "utf8").trim()) || null; } catch { return null; } }
const alive = (pid) => { try { process.kill(pid, 0); return true; } catch { return false; } };

async function main() {
  const missing = [];
  if (!fs.existsSync(CHROME)) missing.push("Google Chrome");
  if (spawnSync("which", ["ffmpeg"]).status !== 0) missing.push("ffmpeg");
  if (!resolveApiKey({ env: process.env, pluginRoot: REPO })) missing.push("OPENAI_API_KEY");
  if (missing.length) { log(`SKIP: missing ${missing.join(", ")}`); process.exitCode = 2; return; }

  if (!fs.existsSync(FIXTURE)) {
    const mk = spawnSync(process.execPath, [path.join(REPO, "test/e2e/make-fixture.mjs")], { stdio: "inherit" });
    if (!check("generate TTS fixture", mk.status === 0)) return;
  }
  const wav = path.join(TMP, "mic.wav");
  const ff = spawnSync("ffmpeg", ["-loglevel", "error", "-y", "-i", FIXTURE, "-af", `adelay=${LEAD_MS}:all=1,apad=pad_dur=50`,
    "-ar", "48000", "-ac", "1", "-c:a", "pcm_s16le", wav]);
  if (!check("fake-mic wav", ff.status === 0 && fs.existsSync(wav))) return;

  inbox = await startFakeInbox(SOCK, {});
  const on = toggle("on");
  if (!check("toggle.sh on", on.status === 0 && /^sotto: voice ON \(/.test(on.out?.stopReason || ""), on.out?.stopReason)) return;
  KEY = fs.readFileSync(path.join(D, "daemon.key"), "utf8").trim();
  const PAGE_SECRET = fs.readFileSync(path.join(D, "page.secret"), "utf8").trim();
  chrome = spawnSilentChrome({ wav, extra: [`--user-data-dir=${path.join(TMP, "chrome-e2e")}`, `${BASE}/?autostart=1#k=${PAGE_SECRET}`] });

  const live = await until(async () => { const s = await status(); return s.state === "live" ? s : null; }, 25000);
  if (!check("state live", !!live)) return;
  liveSince = Date.now();
  liveId = live.live.session_id;

  // The question is delegated and reaches the fake inbox.
  const got = await until(() => (inbox.frames.some((f) => f.type === "user") ? true : null), LEAD_MS + 25000);
  if (!check("question delegated to Claude", !!got)) return;
  const content = inbox.frames.find((f) => f.type === "user").message?.content || "";
  hook("UserPromptSubmit", { session_id: "e2e-relay", prompt_id: "r1", hook_event_name: "UserPromptSubmit", prompt: content });
  const d0 = (await status()).delegations[0];
  await until(async () => ((await status()).delegations.find((x) => x.id === d0?.id)?.status === "delivered" ? true : null), 3000);
  // Let the model's "I'll check with Claude" filler finish before the answer.
  await until(() => {
    const out = readLog().filter((e) => e.ev === "session.output_transcript.delta");
    const last = out[out.length - 1];
    return !last || Date.now() - ts(last) > 1500 ? true : null;
  }, 10000);

  // Claude's markdown-heavy answer through the real Stop forwarder.
  const tStop = Date.now();
  const r = hook("Stop", { session_id: "e2e-relay", prompt_id: "r1", hook_event_name: "Stop", stop_hook_active: false, last_assistant_message: REPORT, background_tasks: [], session_crons: [] });
  check("hook.sh Stop: exit 0, silent", r.status === 0 && r.stdout === "" && r.stderr === "");
  const sent = await until(() => readLog().find((e) => e.ev === "client.send" && e.type === "session.commentary.append" && ts(e) >= tStop - 50), 15000);
  check("result sent as a relay frame, not a quote", !!sent && !/Claude Code's answer/.test(sent.content) && /in your own words/.test(sent.content) && !/\*\*|\/Users|No input needed/i.test(sent.content), sent ? JSON.stringify(sent.content.slice(0, 160)) : "none");
  const acked = sent && await until(() => readLog().find((e) => e.ev === "append.ack" && e.event_id === sent.event_id), 10000);
  check("relay commentary acked", !!acked);
  // From the send, not the ack: speech can start before the ack is logged
  // (the earlier filler already went quiet above).
  const from = sent ? ts(sent) : tStop;

  // What the voice said about it: output deltas after the ack until 3 s of quiet.
  const spoken = await until(() => {
    const ds = readLog().filter((e) => e.ev === "session.output_transcript.delta" && ts(e) >= from);
    if (!ds.length) return null;
    return Date.now() - ts(ds[ds.length - 1]) > 3000 ? ds : null;
  }, 30000);
  const said = spoken ? spoken.map((e) => e.delta).join("").replace(/\s+/g, " ").trim() : "";
  if (spoken) timings.stop_to_speech_start_ms = ts(spoken[0]) - tStop;
  const words = said.split(/\s+/).filter(Boolean).length;
  log(`spoken (${words} words): ${JSON.stringify(said)}`);
  check("the voice spoke about the result", words >= 3, `${words} words`);
  check("no \"Claude Code's answer\" framing", !/claude code'?s answer/i.test(said));
  check("no list or markdown read aloud (bullet, asterisk, label)", !/\bbullets?\b|\basterisks?\b|\bdetails:|\bfixture:|\bused by:|\bgenerated by:/i.test(said));
  check("no file path or file name read aloud", !/\/\w|\b[\w-]+\.(?:m?js|wav|json|md)\b|\b(?:users|dev)\s*\/|slash/i.test(said));
  const tag = said.split(/(?<=[.!?])\s+/).flatMap((x) => [x, x.split(/[,;]\s+/).pop()]).find((x) => isTagline(x));
  check("no stock tag line", !tag && !/(?:no|nothing)(?: else)? (?:input|action)? ?(?:needed|required) (?:from|for) you/i.test(said), tag || "");
  check("no banned opener", !isBannedOpener(said));
  check(`under ${MAX_WORDS} words`, words > 0 && words < MAX_WORDS, `${words} words`);
  check("still carries the key fact (banana split)", /banana/i.test(said));
  const st = await status();
  check("delegation answered", st.delegations.find((x) => x.id === d0?.id)?.status === "answered");

  const off = toggle("off");
  check("toggle.sh off", off.status === 0 && /^sotto: voice OFF\./.test(off.out?.stopReason || ""));
  const closed = await until(() => readLog().find((e) => e.ev === "session.closed" && e.live_id === liveId), 20000);
  billed = closed?.seconds ?? null;
  timings.live_wall_ms = Date.now() - liveSince;
  const raw = fs.readFileSync(path.join(D, "logs", "daemon.log"), "utf8");
  const apiKey = resolveApiKey({ env: process.env, pluginRoot: REPO });
  check("daemon log has no API key, inbox token or daemon key", !raw.includes(apiKey) && !raw.includes(INBOX_TOKEN) && !raw.includes(KEY));
}

async function cleanup() {
  try {
    const h = await fetch(`${BASE}/healthz`, { signal: AbortSignal.timeout(500) }).then((r) => r.json());
    if (h.name === "sotto" && h.state !== "off") {
      await fetch(`${BASE}/control`, { method: "POST", headers: hdr(), body: JSON.stringify({ action: "shutdown" }) }).catch(() => {});
      await sleep(3000);
    }
  } catch { /* daemon already gone */ }
  if (chrome) { try { chrome.kill("SIGTERM"); } catch { /* ignore */ } }
  const pid = daemonPid();
  if (pid && alive(pid)) { try { process.kill(pid, "SIGTERM"); } catch { /* ignore */ } }
  await sleep(500);
  if (chrome) { try { chrome.kill("SIGKILL"); } catch { /* ignore */ } }
  if (pid && alive(pid)) { try { process.kill(pid, "SIGKILL"); } catch { /* ignore */ } }
  if (inbox) await inbox.close().catch(() => {});
  try { fs.unlinkSync(SOCK); } catch { /* ignore */ }
  if (process.env.SOTTO_E2E_KEEP === "1") log(`kept ${TMP}`);
  else fs.rmSync(TMP, { recursive: true, force: true });
}

let budgetBlown = false;
const guard = setInterval(() => {
  if (!liveSince || budgetBlown || Date.now() - liveSince < LIVE_BUDGET_MS) return;
  budgetBlown = true;
  check("finished within the Live budget", false, `${LIVE_BUDGET_MS / 1000} s`);
  fetch(`${BASE}/control`, { method: "POST", headers: hdr(), body: JSON.stringify({ action: "shutdown" }) }).catch(() => {});
}, 1000);
guard.unref();

try {
  await main();
} catch (e) {
  check("no exceptions", false, String(e && e.stack || e));
} finally {
  await cleanup();
  clearInterval(guard);
  const failed = results.filter((r) => !r.ok);
  log("---- timings");
  for (const [k, v] of Object.entries(timings)) log(`${k.padEnd(38)} ${k.endsWith("_ms") ? secs(v) : v}`);
  log("----");
  log(`${failed.length ? "FAIL" : process.exitCode === 2 ? "SKIP" : "PASS"}: ${results.length - failed.length} passed, ${failed.length} failed`);
  log(`live session: ${liveId || "none"}  billed seconds: ${billed ?? "unknown"}`);
  if (failed.length) process.exitCode = 1;
}
